title: "Coding Notes"
description: "A collection of coding tutorials and resources"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lrmulkayhee.github.io/Coding-Notes" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown